spring.application.name=ProgettoPWeb

# H2 Embedded mode database configuration
spring.datasource.url=jdbc:h2:file:./data/fitnessDB;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Forces .sql execution at the start
spring.sql.init.mode=never
spring.thymeleaf.cache=false

# NOTE: init.mode was changed to "never" to disable the database startup when not needed.
#       thymeleaf.cache was also set to false and both must be set back to true when deploying or needed