spring.application.name=ProgettoPWeb

spring.datasource.url=jdbc:h2:mem:fitnessDB
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=h2